source 'https://gitlab.com/TahaElsheikh1/specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'VUIComponents_Example' do
    pod 'VUIComponents', :path => '../'

  target 'VUIComponents_Tests' do
    inherit! :search_paths

    
  end
end
